version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-app
    # Publish FastAPI container on port 8000
    ports:
      - "8000:8000"
    # Make sure it starts after the pgvector container
    depends_on:
      - pgvector

  pgvector:
    image: phidata/pgvector:16
    container_name: pgvector
    # Environment variables for postgres
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      PGDATA: /var/lib/postgresql/data/pgdata
    # Map local port 5532 to container's 5432
    ports:
      - "5532:5432"
    # Named volume for persistent storage
    volumes:
      - pgvolume:/var/lib/postgresql/data

volumes:
  pgvolume:
